language: bash
os:
  - linux
env:
  - FLUTTER_CHANNEL="stable"
  - FLUTTER_CHANNEL="master"
sudo: false
before_script:
  - cd ..
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL
  - export PATH=$PATH:$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin
  - cd -
  - flutter doctor
script:
  - set -e # abort CI if an error happens
  # Change permission
  - chmod 777 scripts/flutter_test.sh
  - ./scripts/flutter_test.sh packages/flutter_shine
  - ./scripts/flutter_test.sh packages/flutter_shine/example

  # export coverage
  - if [ $FLUTTER_CHANNEL = "stable" ]; then
    bash <(curl -s https://codecov.io/bash);
    fi
matrix:
  fast_finish: true
  allow_failures:
    - env: FLUTTER_CHANNEL="master"
cache:
  directories:
    - $HOME/.pub-cache
